### ISSUE TITLE
client response test

### ISSUE THREAD

**Issue by FerrariAlberto** [go-swagger/go-swagger#1006]
hello, 
probably a very noob question but i'm having truble solving it.

how do i test the generated client?
i've generated the client in java and i would like to print to the console the server response and to see if the models i've made in the swagger spec are correct.

sorry for the stupid question

**Comment by FerrariAlberto** [comment]
`public static void main(String args[]){
    	BigDecimal num = new BigDecimal(4);
    	String str = "it_IT";
    	
    	CatalogApi test = new CatalogApi();
    	try {
    		System.out.println(test.restfulShoppingTagsGet(num,str));
    	} catch (ApiException e) {
    		e.printStackTrace();
    	}
     }`

i've inserted this in io.swagger.client.api but i'm getting this error in the console

`io.swagger.client.ApiException: Content type "application/xml" is not supported for type: class io.swagger.client.model.Collection
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:844)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:1035)
	at io.swagger.client.ApiClient.execute(ApiClient.java:969)
	at io.swagger.client.api.CatalogApi.restfulShoppingTagsGetWithHttpInfo(CatalogApi.java:281)
	at io.swagger.client.api.CatalogApi.restfulShoppingTagsGet(CatalogApi.java:266)
	at io.swagger.client.api.CatalogApi.main(CatalogApi.java:327)`

**Comment by gregmarr** [comment]
I think you're in the wrong place. This library only generates in the Go language, not Java.
