### ISSUE TITLE
`swagger generate client` panics

### ISSUE THREAD

**Issue by arekkas** [go-swagger/go-swagger#1181]
## Problem statement

`swagger generate client` panics

## Swagger specification

https://gist.github.com/arekkas/9b3c57b185c58b762a5211b26f641e96

## Steps to reproduce

```
$ go get -u github.com/go-swagger/go-swagger/cmd/swagger
$ swagger generate client -f ./api.swagger.json -A hydrasdk
2017/09/26 14:07:45 building a plan for generation
2017/09/26 14:07:45 planning definitions
2017/09/26 14:07:46 planning operations
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x9 pc=0x957751]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).NewSliceBranch(0xc043d62000, 0xc043fccfc0, 0xc042720001)
        C:/workspace/go/src/github.com/go-swagger/go-swagger/generator/model.go:391 +0x131
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildArray(0xc043d62000, 0x182d9a0, 0xc042daa3c0)
        C:/workspace/go/src/github.com/go-swagger/go-swagger/generator/model.go:1068 +0x14a
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildItems(0xc043d62000, 0x0, 0x0)
        C:/workspace/go/src/github.com/go-swagger/go-swagger/generator/model.go:1104 +0xbfc
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc043d62000, 0xc043708c60, 0xf)
        C:/workspace/go/src/github.com/go-swagger/go-swagger/generator/model.go:1445 +0xab2
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).MakeResponse(0xc04249d600, 0xb9b13a, 0x1, 0xc043708c60, 0xf, 0xb9b301, 0xc04321aab0, 0xc8, 0x0, 0x0, ...)
```

## Environment
swagger version: master
go version: 1.9
OS: Win10 x64

**Comment by arekkas** [comment]
Tried it with 0.12.0 and 0.11.0 with the same result.

**Comment by immesys** [comment]
Same problem here

**Comment by kreamyx** [comment]
The reason is because in the swagger spec, the schema of `clientsList` response is defined as `type: object`. It should be `type: array`

**Comment by immesys** [comment]
Why does swagger validate work?

**Comment by casualjim** [comment]
because it mostly uses a json schema for validation provided by upstream swagger.

**Comment by kreamyx** [comment]
This commit on go-open/validate 
https://github.com/go-openapi/validate/commit/e8b25c4c6cccee94c578fa3bd0d3f5d459290d08 
should fix this problem. We should close this issue if there are no further requirements
