### ISSUE TITLE
Panics on attempt to generate server

### ISSUE THREAD

**Issue by rafecolton** [go-swagger/go-swagger#1192]
## Problem statement

Panic on attempt to generate server (see bottom for output). Note that the spec is valid according to the [validator-badge](https://github.com/swagger-api/validator-badge) tool (running on localhost)

## Swagger specification

2.0

## Steps to reproduce

```bash
swagger generate server -f _spec/spec.yml
```

## Environment
swagger version: [latest](https://github.com/go-swagger/go-swagger/commit/a22e5ec12e68e5b3de1957b38d036cd93ed20f02)  
go version: go version go1.9 darwin/amd64
OS: macOS 10.12.6

## Output

```
panic: interface conversion: interface {} is spec.Schema, not spec.Response

goroutine 1 [running]:
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).validateResponseExample(0xc422289938, 0xc42089cca0, 0x17, 0xc422289688, 0x0)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:645 +0x2e6
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).validateExamplesValidAgainstSchema(0xc422289938, 0xc420b90540)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:671 +0x25d
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.(*SpecValidator).Validate(0xc422289938, 0x1755080, 0xc4207ea6e0, 0x131fa04, 0x16cc0c0)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:125 +0x37b
github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate.Spec(0xc4207ea6e0, 0x1b67b40, 0xc42033d7a0, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/go-openapi/validate/spec.go:51 +0x81
github.com/go-swagger/go-swagger/generator.validateSpec(0x7fff5fbff1e3, 0xe, 0xc4207ea6e0, 0xe, 0xc4207ea6e0)
	/go/src/github.com/go-swagger/go-swagger/generator/shared.go:608 +0x86
github.com/go-swagger/go-swagger/generator.newAppGenerator(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204465a0, 0x157b00a, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:80 +0xae4
github.com/go-swagger/go-swagger/generator.GenerateServer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204465a0, 0xc42082d930, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:39 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc42086be40, 0xc42082d980, 0x0, 0x4, 0xc42086be40, 0x1)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:118 +0x54a
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42084a9c0, 0xc42000e1f0, 0x4, 0x4, 0x100f168, 0x30, 0xc42021a900, 0xc420435f80, 0xc4204358c8)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x893
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc42084a9c0, 0x6, 0x17a413a, 0x6, 0x0, 0x17ec525)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x73
main.main()
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:105 +0x858
```

**Comment by EleanorRigby** [comment]
@rafecolton : Is it possible for you to share  _spec/spec.yml ?

**Comment by casualjim** [comment]
unless we get a spec we can't fix this
