### ISSUE TITLE
Codegen gives SIGSEGV

### ISSUE THREAD

**Issue by ffledgling** [go-swagger/go-swagger#1238]
## Problem statement
Trying to codegen a seemingly valid swagger spec segaults the swagger cli tool.

## Swagger specification
Swagger spec that causes the segfault:
```
swagger: '2.0'
info:
  version: 0.0.1
  title: PowerDNS Authoritative HTTP API
  license:
    name: MIT
host: localhost:8081
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /servers:
    get:
      summary: List all servers
      operationId: listServers
      tags:
        - servers
      responses:
        '200':
          description: An array of servers
          schema:
            $ref: '#/definitions/Servers'

  '/servers/{server_id}':
    get:
      summary: List a server
      operationId: listServer
      tags:
        - servers
      parameters:
        - name: server_id
          in: path
          required: true
          description: The id of the server to retrieve
          type: string
      responses:
        '200':
          description: An server
          schema:
            $ref: '#/definitions/Server'

  '/servers/{server_id}/zones':
    get:
      summary: List all Zones in a server
      operationId: listZones
      tags:
        - zones
      parameters:
        - name: server_id
          in: path
          required: true
          description: The id of the server to retrieve
          type: string
      responses:
        '200':
          description: An array of Zones
          schema:
            $ref: '#/definitions/Zones'

  '/servers/{server_id}/zones/{zone_id}':
    get:
      summary: zone managed by a server
      operationId: listZone
      tags:
        - zones
      parameters:
        - name: server_id
          in: path
          required: true
          description: The id of the server to retrieve
          type: string
        - name: zone_id
          type: string
          in: path
          required: true
          description: The id of the zone to retrieve
      responses:
        '200':
          description: A Zone
          schema:
            $ref: '#/definitions/Zone'


definitions:
  Server:
    properties:
      type:
        type: string
        description: 'Set to “Server”'
      id:
        type: string
        description: 'The id of the server, “localhost”'
      daemon_type:
        type: string
        description: '“recursor” for the PowerDNS Recursor and “authoritative” for the Authoritative Server'
      version:
        type: string
        description: 'The version of the server software'
      url:
        type: string
        description: 'The API endpoint for this server'
      config_url:
        type: string
        description: 'The API endpoint for this server’s configuration'
      zones_url:
        type: string
        description: 'The API endpoint for this server’s zones'

  Servers:
    type: array
    items:
      $ref: '#/definitions/Server'

  Zone:
    properties:
      id:
        type: string
        description: 'Opaque zone id (string), assigned by the server, should not be interpreted by the application. Guaranteed to be safe for embedding in URLs.'
      name:
        type: string
        description: 'Name of the zone (e.g. “example.com.”) MUST have a trailing dot'
      type:
        type: string
        description: 'Set to “Zone”'
      url:
        type: string
        description: 'API endpoint for this zone'
      kind:
        type: string
        enum:
          - 'Native'
          - 'Master'
          - 'Slave'
        description: 'Zone kind, one of “Native”, “Master”, “Slave”'
      rrsets:
        type: object
        items:
          $ref: '#/definitions/RRSets'
        description: 'RRSets in this zone'
      serial:
        type: integer
        description: 'The SOA serial number'
      notified_serial:
        type: integer
        description: 'The SOA serial notifications have been sent out for'
      masters:
        type: array
        items:
          type: string
        description: ' List of IP addresses configured as a master for this zone (“Slave” type zones only)'
      dnssec:
        type: boolean
        description: 'Whether or not this zone is DNSSEC signed (inferred from presigned being true XOR presence of at least one cryptokey with active being true)'
      nsec3param:
        type: string
        description: 'The NSEC3PARAM record'
      nsec3narrow:
        type: boolean
        description: 'Whether or not the zone uses NSEC3 narrow'
      presigned:
        type: boolean
        description: 'Whether or not the zone is pre-signed'
      soa_edit:
        type: string
        description: 'The SOA-EDIT metadata item'
      soa_edit_api:
        type: string
        description: 'The SOA-EDIT-API metadata item'
      api_rectify:
        type: boolean
        description: ' Whether or not the zone will be rectified on data changes via the API'
      zone:
        type: string
        description: 'MAY contain a BIND-style zone file when creating a zone'
      account:
        type: string
        description: 'MAY be set. Its value is defined by local policy'
      nameservers:
        type: array
        items:
          type: string
        description: 'MAY be sent in client bodies during creation, and MUST NOT be sent by the server. Simple list of strings of nameserver names, including the trailing dot. Not required for slave zones.'

  Zones:
    type: array
    items:
      $ref: '#/definitions/Zone'

  RRSets:
    type: array
    items:
      $ref: '#/definitions/RRSet'

  RRSet:
    properties:
      name:
        type: string
        description: 'Name for record set (e.g. “www.powerdns.com.”)'
      type:
        type: string
        description: 'Type of this record (e.g. “A”, “PTR”, “MX”)'
      ttl:
        type: integer
        description: 'DNS TTL of the records, in seconds. MUST NOT be included when changetype is set to “DELETE”.'
      changetype:
        type: string
        description: 'MUST be added when updating the RRSet. Must be REPLACE or DELETE. With DELETE, all existing RRs matching name and type will be deleted, including all comments. With REPLACE: when records is present, all existing RRs matching name and type will be deleted, and then new records given in records will be created. If no records are left, any existing comments will be deleted as well. When comments is present, all existing comments for the RRs matching name and type will be deleted, and then new comments given in comments will be created.'
      records:
        type: array
        description: 'All records in this RRSet. When updating Records, this is the list of new records (replacing the old ones). Must be empty when changetype is set to DELETE. An empty list results in deletion of all records (and comments).'
        items:
          $ref: '#/definitions/Record'
      comments:
        type: array
        description: 'List of Comment. Must be empty when changetype is set to DELETE. An empty list results in deletion of all comments. modified_at is optional and defaults to the current server time.'
        items:
          $ref: '#/definitions/Comment'

  Record:
    properties:
      content:
        type: string
        description: 'The content of this record'
      disabled:
        type: boolean
        description: 'Whether or not this record is disabled'
      set-ptr:
        type: boolean
        description: 'f set to true, the server will find the matching reverse zone and create a PTR there. Existing PTR records are replaced. If no matching reverse Zone, an error is thrown. Only valid in client bodies, only valid for A and AAAA types. Not returned by the server.'

  Comment:
    properties:
      content:
        type: string
        description: 'The actual comment'
      account:
        type: string
        description: 'Name of an account that added the comment'
      modifided_at:
        type: integer
        description: 'Timestamp of the last change to the comment'
```

While the spec is very large, I think the relevant part has something to do with nesting an object in the schema definition. The following patch to the above spec seems to make the problem go away (authoritative-api-swagger.yaml is the working version while the .bkp is the borked one):

```
$ diff authoritative-api-swagger.yaml{,.bkp}
27,29d26
<             #type: array
<             #items:
<             #  $ref: '#/definitions/Server'
66,68d62
<             #type: array
<             #items:
<             #  $ref: '#/definitions/Zone'
146c140
<         type: array
---
>         type: object
148c142
<           $ref: '#/definitions/RRSet'
---
>           $ref: '#/definitions/RRSets'
```

## Steps to reproduce

```
$ swagger validate authoritative-api-swagger.yaml.bkp
The swagger spec at "authoritative-api-swagger.yaml.bkp" is valid against swagger specification 2.0
swagger generate client -f authoritative-api-swagger.yaml -A pdns-go

$ swagger generate client -f authoritative-api-swagger.yaml.bkp -A pdns-go
2017/10/30 18:16:40 building a plan for generation
2017/10/30 18:16:40 planning definitions
DEBUG: name - %v RRSets
DEBUG: name - %v rrsets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe pc=0x9608ab]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).NewSliceBranch(0xc421706c00, 0xc421b966c0, 0x1)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:388 +0x60b
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildArray(0xc421706c00, 0x0, 0x0)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:1082 +0xd5
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildItems(0xc421706c00, 0x0, 0x0)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:1118 +0xc8e
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc421706c00, 0xc420cfd8f0, 0x6)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:1459 +0xa6f
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildProperties(0xc421706000, 0xc4217062c0, 0xc4228759b8)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:674 +0x304
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc421706000, 0x0, 0xc421c01a10)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:1447 +0x9a6
github.com/go-swagger/go-swagger/generator.makeGenDefinitionHierarchy(0xc420d37ce0, 0x4, 0xc421337db0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:166 +0x31a
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc420d37ce0, 0x4, 0xc421337db0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/model.go:133 +0xbc
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc42031ad20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/support.go:602 +0x5d9
github.com/go-swagger/go-swagger/generator.(*clientGenerator).Generate(0xc42031ad20, 0xc42031ad20, 0x6)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/client.go:117 +0x78
github.com/go-swagger/go-swagger/generator.GenerateClient(0x7ffc9828b199, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4204165a0, 0xc4204c7c98, ...)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/generator/client.go:109 +0x751
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).Execute(0xc42080fe00, 0xc42081e420, 0x0, 0x6, 0xc42080fe00, 0x1)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:103 +0x41c
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42081e3c0, 0xc4200100f0, 0x6, 0x6, 0x410a98, 0x30, 0xc4202f2a20, 0xc4201ed580, 0xc4201ece48)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x893
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc42081e3c0, 0x6, 0xbaa9d7, 0x6, 0x0, 0xbf3197)
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x73
main.main()
        /spare/local/ajaisingh/goworkspace/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:105 +0x858
```

## Environment
swagger version: 2.0  
go version: go version go1.8.3 linux/amd64  
OS: Ubuntu 16.04

**Comment by gregmarr** [comment]
This is likely your problem:

      rrsets:
        type: object
        items:
          $ref: '#/definitions/RRSets'
        description: 'RRSets in this zone'

`items` is for `array`, not `object`.  If you want to embed that directly, just do this:

      rrsets:
        $ref: '#/definitions/RRSets'
 
Note that you can't then have a `description` there with the `$ref`.

**Comment by ffledgling** [comment]
@gregmaar You're right, except the validator does not seem to error out, which I was hoping it would.

**Comment by gregmarr** [comment]
Interesting.  The spec doesn't actually say that `items` is not valid for `object`, only that it's required for `array`.  That might be why the validator doesn't catch it.

**Comment by ffledgling** [comment]
@gregmarr Is that a problem in the spec definition or in the codegen/parser?

**Comment by gregmarr** [comment]
I honestly have no idea, @casualjim will need to chime in here.

**Comment by kreamyx** [comment]
This issue has been addressed in go-openapi/validate https://github.com/go-openapi/validate/pull/32 but the changes are not pulled to go-swagger/vendor yet

**Comment by casualjim** [comment]
I just merged those changes into master on go-swagger/go-swagger

**Comment by fredbi** [comment]
I verified that the current version correctly detects this as a spec error.
Made a shorter fixture to reproduce the case.
I'll push PR to add this check as a fixture in UT

**Comment by fredbi** [comment]
This issue should be closed now
