### ISSUE TITLE
dep ensure hangs indefinitely on Ubuntu when github 404 is in required

### ISSUE THREAD

**Issue by davidmi** [go-swagger/go-swagger#1506]
## Problem statement
When a github project that 404s is added to required, `dep ensure` hangs indefinitely. I unfortunately ran into this when I added a url with a typo...

## Steps to reproduce

```
> cat Gopkg.toml
required = ["github.com/doesnotexist/doesnotexist"]

[prune]
  go-tests = true
  unused-packages = true
```

Then run `dep ensure`. It will hang at `Signal received: waiting for 1 ops to complete...`. Then you have to ctrl-c again or send sigangry with ctrl-\ since it hangs there as well.

I believe the root cause is that the program does not differentiate between a 404 and a private repo -- I've managed to get the following output intermittently:

```
 	(1) failed to list versions for https://github.com/doesnotexist/doesnotexist: fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

Proposed resolution: Make an http request to github repos to detect 404 before git cloning, or terminate on prompts from git immediately.

## Environment
go version: go version go1.10 linux/amd64

  
OS:  Ubuntu 16.04

## Debugging:
Output on termination, ctrl-c and then ctrl-\ to send sigangry because ctrl-c also hangs:

```
> dep ensure
^CSignal received: waiting for 1 ops to complete...
^C^\SIGQUIT: quit
PC=0x45ba91 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0xc00848, 0x0, 0x0, 0x0, 0x7ffe00000000, 0x0, 0x0, 0x0, 0x7ffe8b53fce8, 0x410cfb, ...)
	/home/diserovich/go/src/runtime/sys_linux_amd64.s:526 +0x21
runtime.futexsleep(0xc00848, 0x7ffe00000000, 0xffffffffffffffff)
	/home/diserovich/go/src/runtime/os_linux.go:45 +0x4b
runtime.notesleep(0xc00848)
	/home/diserovich/go/src/runtime/lock_futex.go:151 +0x9b
runtime.stoplockedm()
	/home/diserovich/go/src/runtime/proc.go:2096 +0x8c
runtime.schedule()
	/home/diserovich/go/src/runtime/proc.go:2488 +0x2da
runtime.park_m(0xc42007ea80)
	/home/diserovich/go/src/runtime/proc.go:2599 +0xb6
runtime.mcall(0x0)
	/home/diserovich/go/src/runtime/asm_amd64.s:351 +0x5b

goroutine 1 [syscall]:
syscall.Syscall6(0xf7, 0x1, 0x3ba, 0xc4200f9c88, 0x1000004, 0x0, 0x0, 0x0, 0xc42007c000, 0x0)
	/home/diserovich/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420234780, 0x0, 0x0, 0x3)
	/home/diserovich/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc420234780, 0xc42021e6c0, 0x0, 0xc42007c000)
	/home/diserovich/go/src/os/exec_unix.go:22 +0x3c
os.(*Process).Wait(0xc420234780, 0x96ebf8, 0x96ec00, 0x96ebf0)
	/home/diserovich/go/src/os/exec.go:123 +0x2b
os/exec.(*Cmd).Wait(0xc420262420, 0x96e438, 0x9ba6a0)
	/home/diserovich/go/src/os/exec/exec.go:461 +0x5c
github.com/golang/dep/gps.cmd.CombinedOutput(0x9ba6a0, 0xc42022a5f0, 0xc420262420, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/gps/cmd_unix.go:80 +0x160
github.com/golang/dep/gps.(*gitSource).listVersions(0xc420236330, 0x9ba6a0, 0xc42022a5f0, 0x435c54, 0xc4200fa250, 0x412568, 0x10, 0x8d3300)
	/home/diserovich/test/src/github.com/golang/dep/gps/vcs_source.go:233 +0x2f2
github.com/golang/dep/gps.(*sourceGateway).loadLatestVersionList.func1(0x9ba6a0, 0xc42022a5f0, 0x9ba3a0, 0xc4200b5b80)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:593 +0x6d
github.com/golang/dep/gps.(*supervisor).do(0xc42008d8c0, 0x9ba3e0, 0xc4200ac018, 0x94a252, 0x3, 0x1, 0xc4200fa368, 0x0, 0xc4200fa370)
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:675 +0xd5
github.com/golang/dep/gps.(*sourceGateway).loadLatestVersionList(0xc42022a550, 0x9ba3e0, 0xc4200ac018, 0xc42022a5a0, 0x50, 0x50)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:591 +0xf8
github.com/golang/dep/gps.(*sourceGateway).sourceExistsUpstream(0xc42022a550, 0x9ba3e0, 0xc4200ac018, 0x0, 0xc4200fa448, 0x412568)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:557 +0x63
github.com/golang/dep/gps.(*sourceGateway).require(0xc42022a550, 0x9ba3e0, 0xc4200ac018, 0xc400000001, 0x778375, 0x8cdb00)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:617 +0x178
github.com/golang/dep/gps.newSourceGateway(0x9ba3e0, 0xc4200ac018, 0x9be900, 0xc420236330, 0xc42008d8c0, 0xc4201b5ea0, 0x1d, 0x0, 0x0, 0xc420232560)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:284 +0x216
github.com/golang/dep/gps.(*sourceCoordinator).getSourceGatewayFor(0xc4201d35e0, 0x9ba3e0, 0xc4200ac018, 0xc420234330, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:219 +0xad1
github.com/golang/dep/gps.(*SourceMgr).SourceExists(0xc42008d920, 0xc420234330, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:489 +0x88
github.com/golang/dep/gps.(*bridge).SourceExists(0xc420222810, 0xc420234330, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/gps/bridge.go:124 +0x93
github.com/golang/dep/gps.(*solver).createVersionQueue(0xc42024e5a0, 0xc420234330, 0x24, 0x0, 0x0, 0xc420236290, 0x1, 0x1, 0x0, 0x0, ...)
	/home/diserovich/test/src/github.com/golang/dep/gps/solver.go:811 +0xed
github.com/golang/dep/gps.(*solver).solve(0xc42024e5a0, 0x9ba3e0, 0xc4200ac018, 0x40, 0x40, 0x8)
	/home/diserovich/test/src/github.com/golang/dep/gps/solver.go:517 +0x5b7
github.com/golang/dep/gps.(*solver).Solve(0xc42024e5a0, 0x9ba3e0, 0xc4200ac018, 0xc4202260e0, 0x20, 0x20, 0xc420222200)
	/home/diserovich/test/src/github.com/golang/dep/gps/solver.go:457 +0xe4
main.(*ensureCommand).runDefault(0xc42019f916, 0xc42008d0e0, 0xc420159740, 0x0, 0x0, 0xc42008d140, 0x9bdae0, 0xc42008d920, 0xc420026064, 0x1e, ...)
	/home/diserovich/test/src/github.com/golang/dep/cmd/dep/ensure.go:301 +0x168
main.(*ensureCommand).Run(0xc42019f916, 0xc42008d0e0, 0xc420159740, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/cmd/dep/ensure.go:219 +0x867
main.(*Config).Run(0xc42008cfc0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/cmd/dep/main.go:232 +0x10e5
main.main()
	/home/diserovich/test/src/github.com/golang/dep/cmd/dep/main.go:69 +0x52c

goroutine 20 [syscall]:
os/signal.signal_recv(0x9b7a40)
	/home/diserovich/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/home/diserovich/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/home/diserovich/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 21 [select, locked to thread]:
runtime.gopark(0x96eff8, 0x0, 0x94b32f, 0x6, 0x18, 0x1)
	/home/diserovich/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42003ff50, 0xc42008e4e0)
	/home/diserovich/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/home/diserovich/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/home/diserovich/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 22 [semacquire]:
sync.runtime_notifyListWait(0xc42008d8e8, 0xc400000000)
	/home/diserovich/go/src/runtime/sema.go:510 +0x10b
sync.(*Cond).Wait(0xc42008d8d8)
	/home/diserovich/go/src/sync/cond.go:56 +0x80
github.com/golang/dep/gps.(*supervisor).wait(0xc42008d8c0)
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:743 +0x43
github.com/golang/dep/gps.(*SourceMgr).Release.func1()
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:391 +0x45
sync.(*Once).Do(0xc42008d970, 0xc4200406c0)
	/home/diserovich/go/src/sync/once.go:44 +0xbe
github.com/golang/dep/gps.(*SourceMgr).Release(0xc42008d920)
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:388 +0x52
github.com/golang/dep/gps.(*SourceMgr).HandleSignals.func1(0xc42008d920, 0xc42008d980, 0xc42008e5a0)
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:345 +0x194
created by github.com/golang/dep/gps.(*SourceMgr).HandleSignals
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:330 +0xb2

goroutine 35 [semacquire]:
sync.runtime_Semacquire(0xc4201d3604)
	/home/diserovich/go/src/runtime/sema.go:56 +0x39
sync.(*RWMutex).RLock(0xc4201d35f8)
	/home/diserovich/go/src/sync/rwmutex.go:50 +0x49
github.com/golang/dep/gps.(*sourceCoordinator).getSourceGatewayFor(0xc4201d35e0, 0x9ba3e0, 0xc4200ac018, 0xc420234330, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/gps/source.go:94 +0xc6
github.com/golang/dep/gps.(*SourceMgr).SyncSourceFor(0xc42008d920, 0xc420234330, 0x24, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/test/src/github.com/golang/dep/gps/source_manager.go:513 +0x82
github.com/golang/dep/gps.(*bridge).SyncSourceFor(0xc420222810, 0xc420234330, 0x24, 0x0, 0x0, 0xc42022a280, 0x1)
	/home/diserovich/test/src/github.com/golang/dep/gps/bridge.go:214 +0x5b
created by github.com/golang/dep/gps.(*solver).selectRoot
	/home/diserovich/test/src/github.com/golang/dep/gps/solver.go:644 +0x614

goroutine 40 [IO wait]:
internal/poll.runtime_pollWait(0x7f0bd9d92f00, 0x72, 0xc420260ce8)
	/home/diserovich/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42022a6a8, 0x72, 0xffffffffffffff01, 0x9b5660, 0xbc4540)
	/home/diserovich/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42022a6a8, 0xc4202a0001, 0x200, 0x200)
	/home/diserovich/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42022a690, 0xc4202a0000, 0x200, 0x200, 0x0, 0x0, 0x0)
	/home/diserovich/go/src/internal/poll/fd_unix.go:157 +0x17d
os.(*File).read(0xc4202280c0, 0xc4202a0000, 0x200, 0x200, 0xc4202a0000, 0x0, 0x0)
	/home/diserovich/go/src/os/file_unix.go:226 +0x4e
os.(*File).Read(0xc4202280c0, 0xc4202a0000, 0x200, 0x200, 0x0, 0x0, 0xc420260e60)
	/home/diserovich/go/src/os/file.go:107 +0x6a
bytes.(*Buffer).ReadFrom(0xc4202382a0, 0x9b4aa0, 0xc4202280c0, 0x7f0bd9d0e020, 0xc4202382a0, 0x1)
	/home/diserovich/go/src/bytes/buffer.go:205 +0xa0
io.copyBuffer(0x9b4080, 0xc4202382a0, 0x9b4aa0, 0xc4202280c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/diserovich/go/src/io/io.go:386 +0x31a
io.Copy(0x9b4080, 0xc4202382a0, 0x9b4aa0, 0xc4202280c0, 0x0, 0x0, 0x0)
	/home/diserovich/go/src/io/io.go:362 +0x5a
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/home/diserovich/go/src/os/exec/exec.go:275 +0x4d
os/exec.(*Cmd).Start.func1(0xc420262420, 0xc4202325c0)
	/home/diserovich/go/src/os/exec/exec.go:396 +0x27
created by os/exec.(*Cmd).Start
	/home/diserovich/go/src/os/exec/exec.go:395 +0x5df

goroutine 41 [chan receive]:
github.com/golang/dep/gps.cmd.CombinedOutput.func1(0x9ba6a0, 0xc42022a5f0, 0xc420262420, 0xc42021e6c0)
	/home/diserovich/test/src/github.com/golang/dep/gps/cmd_unix.go:74 +0x203
created by github.com/golang/dep/gps.cmd.CombinedOutput
	/home/diserovich/test/src/github.com/golang/dep/gps/cmd_unix.go:63 +0x152

rax    0xca
rbx    0xc00700
rcx    0x45ba93
rdx    0x0
rdi    0xc00848
rsi    0x0
rbp    0x7ffe8b53fcb0
rsp    0x7ffe8b53fc68
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xc42003ff68
r13    0xff
r14    0xff
r15    0xf
rip    0x45ba91
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

Strace output:
```
...
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3174006528, u64=139666920537856}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 5, 0xc4200e6edc) = -1 EPERM (Operation not permitted)
fstat(5, {st_mode=S_IFREG|0600, st_size=5, ...}) = 0
read(5, "1542\n", 517)                  = 5
read(5, "", 512)                        = 0
close(5)                                = 0
kill(1542, SIG_0)                       = -1 ESRCH (No such process)
unlinkat(AT_FDCWD, "/home/diserovich/test/pkg/dep/sm.lock", 0) = 0
openat(AT_FDCWD, "/home/diserovich/test/pkg/dep/sm.lock.843843724", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600) = 5
epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3174006528, u64=139666920537856}}) = -1 EPERM (Operation not permitted)
epoll_ctl(4, EPOLL_CTL_DEL, 5, 0xc4200e6e84) = -1 EPERM (Operation not permitted)
getpid()                                = 1622
write(5, "1622\n", 5)                   = 5
linkat(AT_FDCWD, "/home/diserovich/test/pkg/dep/sm.lock.843843724", AT_FDCWD, "/home/diserovich/test/pkg/dep/sm.lock", 0) = 0
lstat("/home/diserovich/test/pkg/dep/sm.lock.843843724", {st_mode=S_IFREG|0600, st_size=5, ...}) = 0
lstat("/home/diserovich/test/pkg/dep/sm.lock", {st_mode=S_IFREG|0600, st_size=5, ...}) = 0
close(5)                                = 0
unlinkat(AT_FDCWD, "/home/diserovich/test/pkg/dep/sm.lock.843843724", 0) = 0
close(3)                                = 0
unlinkat(AT_FDCWD, "/home/diserovich/test/pkg/dep/sm.lock.861287841", 0) = 0
futex(0xc420046d48, FUTEX_WAKE, 1)      = 1
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT ILL TRAP ABRT BUS FPE SEGV TERM STKFLT CHLD PROF SYS RTMIN RT_1], NULL, 8) = 0
futex(0xc420046d48, FUTEX_WAKE, 1)      = 1
rt_sigprocmask(SIG_SETMASK, ~[HUP INT QUIT ILL TRAP ABRT BUS FPE SEGV TERM STKFLT CHLD PROF SYS RTMIN RT_1], NULL, 8) = 0
futex(0xc420046948, FUTEX_WAKE, 1)      = 1
futex(0xc00848, FUTEX_WAIT, 0, NULL)    = 0
futex(0xc00848, FUTEX_WAIT, 0, NULL
```

**Comment by casualjim** [comment]
I think you want to report this on the https://github.com/golang/dep repo not here.
