### ISSUE TITLE
Generate Server - panic if "type" missing

### ISSUE THREAD

**Issue by kenjones-cisco** [go-swagger/go-swagger#1648]
## Problem statement

During code generation for server, a panic occurs if the `type` is missing for an attribute of a model when the `format` is specified.

```
2018/08/02 14:05:13 preprocessing spec with option:  minimal flattening
2018/08/02 14:05:13 building a plan for generation
2018/08/02 14:05:13 planning definitions
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*typeResolver).resolveFormat(0xc4206e3ae0, 0xc421314fc0, 0xbe0001, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/types.go:262 +0x587
github.com/go-swagger/go-swagger/generator.(*typeResolver).ResolveSchema(0xc4206e3ae0, 0xc421314fc0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/types.go:644 +0x38d
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildProperties(0xc42078a600, 0x4a, 0xc421dbcda8)
        /go/src/github.com/go-swagger/go-swagger/generator/model.go:690 +0x585
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc42078a600, 0xc42078a600, 0xc421dbec30)
        /go/src/github.com/go-swagger/go-swagger/generator/model.go:1864 +0xe73
github.com/go-swagger/go-swagger/generator.makeGenDefinitionHierarchy(0xc422fe65e0, 0xc, 0xc42039d290, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/model.go:235 +0x2dd
github.com/go-swagger/go-swagger/generator.makeGenDefinition(0xc422fe65e0, 0xc, 0xc42039d290, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/model.go:135 +0xbc
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc422050000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/support.go:542 +0x64a
github.com/go-swagger/go-swagger/generator.(*appGenerator).Generate(0xc422050000, 0x9, 0x0)
        /go/src/github.com/go-swagger/go-swagger/generator/support.go:198 +0xba
github.com/go-swagger/go-swagger/generator.GenerateServer(0x7fffb7323d19, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420116600, 0xc4202e4540, ...)
        /go/src/github.com/go-swagger/go-swagger/generator/support.go:43 +0xcb
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).generate(0xc4203d4680, 0xc420116600, 0x0, 0x0)
        /go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:86 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0x101a2c0, 0xc4203d4680, 0x7e8a01, 0x7fce34746c80)
        /go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/shared.go:157 +0x1ba
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc4203d4680, 0xc42042ac30, 0x0, 0xd, 0xc4203d4680, 0x1)
        /go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:110 +0x37
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc42005db60, 0xc4200100f0, 0xd, 0xd, 0x4128b8, 0xc420088b40, 0xc42004f500, 0xc4203f3101, 0xc420393b60)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x841
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc42005db60, 0x6, 0xbe680e, 0x6, 0x0, 0xc30236)
        /go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
        /go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:140 +0xd8d
```

The API spec should be fixed to properly specify the `type` but a panic makes it difficult to understand what the root issue is.

I traced the issue back to #1638
https://github.com/go-swagger/go-swagger/blob/master/generator/types.go#L262

Either in [ResolveSchema](https://github.com/go-swagger/go-swagger/blob/master/generator/types.go#L262)
or in [resolveFormat](https://github.com/go-swagger/go-swagger/blob/master/generator/types.go#L259) check if the `type` was specified or not when `format` is found instead of assuming it was actually provided.

**Comment by gregmarr** [comment]
There is a function for this, which should be used instead of that line: `tn := t.firstType(schema)`.  Can you try that out?
