### ISSUE TITLE
Golang 1.11 : "swagger generate spec" fail  > "assignment to entry in nil map"

### ISSUE THREAD

**Issue by ariden83** [go-swagger/go-swagger#1735]
## Problem statement

When I run  `swagger generate spec -o https://petstore.swagger.io/v2/swagger.json`

I've got this error : 

```panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/go-swagger/go-swagger/scan.(*setOpParams).Parse(0xc0107699e0, 0xc00bf64d00, 0xa, 0x10, 0x0, 0xc00bf64aa0)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/route_params.go:137 +0x65e
github.com/go-swagger/go-swagger/scan.(*tagParser).Parse(0xc000447398, 0xc00bf64d00, 0xa, 0x10, 0x0, 0xc00bf64d00)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/scanner.go:558 +0x52
github.com/go-swagger/go-swagger/scan.(*sectionedParser).Parse(0xc000447a00, 0xc010769620, 0xc0004476f0, 0xf)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/scanner.go:944 +0x90b
github.com/go-swagger/go-swagger/scan.(*routesParser).Parse(0xc0244c4dc0, 0xc00418af80, 0xb2a560, 0xc004dcb930, 0xc02353e060, 0xc02353e090, 0xc006796ee0, 0xb)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/routes.go:110 +0xd07
github.com/go-swagger/go-swagger/scan.(*appScanner).parseRoutes(0xc02346ba80, 0xc00418af80, 0x0, 0x0)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/scanner.go:423 +0xda
github.com/go-swagger/go-swagger/scan.(*appScanner).Parse(0xc02346ba80, 0xc02346ba80, 0x0, 0x0)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/scanner.go:351 +0x27c
github.com/go-swagger/go-swagger/scan.Application(0xaf725c, 0x1, 0x0, 0x0, 0xaccd68, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/scan/scanner.go:186 +0x72
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*SpecFile).Execute(0xc0000c2370, 0xc0003cd280, 0x0, 0x4, 0xc0000c2370, 0x1)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/spec.go:61 +0x196
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000073bc0, 0xc00001e060, 0x4, 0x4, 0x40dab8, 0x30, 0xb73660, 0xc000092b40, 0xc000441680)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x800
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc000073bc0, 0x6, 0xbc3437, 0x6, 0x0, 0xc0d937)
	/home/adrien/work/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71```

## Swagger installation : 

I use swagger wit go version 1.8, and it's work well, but today, I switch to go 1.11 version. I reinstall go-swagger with : 

```docker pull quay.io/goswagger/swagger

alias swagger="docker run --rm -it -e GOPATH=$HOME/go:/go -v $HOME:$HOME -w $(pwd) quay.io/goswagger/swagger"
swagger version
```

And I got this error

## Environment
swagger version: dev
go version: 1.11
OS:  Ubuntu 16.04.3 LTS

**Comment by casualjim** [comment]
You want to run with: `swagger generate server -f`
The spec will scan go packages
