### ISSUE TITLE
generated server fails spec spec contains  paths differning only by trailing slash

### ISSUE THREAD

**Issue by anz-rfc** [go-swagger/go-swagger#1858]
## Problem statement

`swagger generate server` generates a server that fails when the swagger spec contains multiple operations for similar paths that differ only by a trailing slash.

Expected behaviour: generated server starts serving.

Observed behaviour when server is started:

```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x7bcb7b]

goroutine 1 [running]:
github.com/go-openapi/analysis.(*Spec).SafeParamsFor(0xc000351f40, 0x94d482, 0x4, 0xc0002f2910, 0xd, 0x0, 0x94d482)
	/tmp/swagger_demo/vendor/github.com/go-openapi/analysis/analyzer.go:666 +0x1db
github.com/go-openapi/analysis.(*Spec).ParamsFor(0xc000351f40, 0x94d482, 0x4, 0xc0002f2910, 0xd, 0x9e2be0)
	/tmp/swagger_demo/vendor/github.com/go-openapi/analysis/analyzer.go:651 +0x5c
github.com/go-openapi/runtime/middleware.(*defaultRouteBuilder).AddRoute(0xc0002b55f0, 0x94d482, 0x4, 0xc0002f2910, 0xd, 0xc0004ca1c0)
	/tmp/swagger_demo/vendor/github.com/go-openapi/runtime/middleware/router.go:419 +0x306
github.com/go-openapi/runtime/middleware.DefaultRouter(0xc0004c0050, 0x9e9ba0, 0xc00016e000, 0x8dd0a0, 0xc0002dab10)
	/tmp/swagger_demo/vendor/github.com/go-openapi/runtime/middleware/router.go:139 +0x14c
github.com/go-openapi/runtime/middleware.NewRouter(0xc0002b5080, 0x9e3ac0, 0xc0002dab10, 0xc0002dab10, 0xc0000e0900)
	/tmp/swagger_demo/vendor/github.com/go-openapi/runtime/middleware/router.go:71 +0xe2
github.com/go-openapi/runtime/middleware.(*Context).RoutesHandler(0xc0002b5080, 0x973a78, 0xd0a8ef9d1aa790d5, 0x20)
	/tmp/swagger_demo/vendor/github.com/go-openapi/runtime/middleware/context.go:581 +0x7c
github.com/go-openapi/runtime/middleware.(*Context).APIHandler(0xc0002b5080, 0x0, 0x7f54f0d187e8, 0xc00000cae8)
	/tmp/swagger_demo/vendor/github.com/go-openapi/runtime/middleware/context.go:572 +0xfa
example.com/swagger_demo/restapi/operations.(*BananaAPI).Serve(0xc00016e000, 0x0, 0x0, 0x7f54f2f796c0)
	/tmp/swagger_demo/restapi/operations/banana_api.go:270 +0x80
example.com/swagger_demo/restapi.(*Server).Serve(0xc0000da000, 0x973488, 0xc0000da000)
	/tmp/swagger_demo/restapi/server.go:168 +0x13f9
main.main()
	/tmp/swagger_demo/main.go:35 +0x1dd
```

## Swagger specification

assume there is a file `api.yaml` containing the following:

```
swagger: '2.0'
info:
  description: Banana API
  version: 0.0.0
  title: Banana API
schemes:
  - http
paths:
  /fruit/banana:
    get:
      operationId: GetBanana
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/BananaResponse'
  /fruit/banana/:
    post:
      operationId: PostBanana
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/BananaResponse'
definitions:
  BananaResponse:
    type: object
    properties:
      status:
        type: string
```

## Steps to reproduce

put `api.yaml` in directory alongside following `Dockerfile`:

```
FROM golang:alpine as builder

RUN apk add --no-cache git

# Install swagger from source from current master branch
RUN go get -u github.com/go-swagger/go-swagger/cmd/swagger

ENV WORKDIR=/tmp/swagger_demo
RUN mkdir -p $WORKDIR
WORKDIR $WORKDIR
COPY api.yaml $WORKDIR/api.yaml

RUN go mod init example.com/swagger_demo
RUN swagger version
RUN swagger validate api.yaml
RUN swagger generate server -f api.yaml -A banana -t .
RUN go mod vendor
# n.b. golang:alpine doesnt support CGO, turn it off.
RUN CGO_ENABLED=0 go build -a -v -mod=vendor ./cmd/banana-server

FROM scratch

WORKDIR /root/

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /tmp/swagger_demo/banana-server banana-server

ENTRYPOINT ["./banana-server"]
```

build and run container with:

```
docker build  -f Dockerfile -t swagger_demo:latest . && docker run --rm -it swagger_demo:latest
```

## Environment
swagger version:  whatever `go get -u github.com/go-swagger/go-swagger/cmd/swagger` installs.

```
Linux 9b01c0d28bf2 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 Linux

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.1
PRETTY_NAME="Alpine Linux v3.8"

go version go1.11.4 linux/amd64
```

**Comment by anz-rfc** [comment]
older issue related to trailing slashes: https://github.com/go-swagger/go-swagger/issues/899

**Comment by anz-rfc** [comment]
From my attempt to debug the issue:

* github.com/go-openapi/analysis stores paths including the trailing slash
* github.com/go-openapi/runtime/middleware has various bits of code calling `path.Clean` or `path.Join` -- these both remove trailing slashes from paths (if any)
* code in github.com/go-openapi/runtime/middleware that calls github.com/go-openapi/analysis seems to assume it removes trailing slashes, but it seems like this assumption is wrong, hence the crash at runtime.
* code generated by `swagger generate server` normalises away the trailing slash. For example, the generated code in `restapi/operations/banana_api.go` will contain something like `o.handlers["POST"]["/fruit/banana"] = <...>`.  Note that the trailing slash that was featured in the `api.yaml` spec has been lost.

**Comment by fredbi** [comment]
What would be a sensible enhancement here would be to detect this situation at codegen time and avoid the generation altogether. What I don't like here is the panic at runtime.

**Comment by casualjim** [comment]
a trailing slash is not a meaningful character, we have to normalize to either with or without.
They are largely treated equivalent by clients and servers and we have to normalize paths for url matching

https://tools.ietf.org/html/rfc3986#section-6.2.4
https://play.golang.org/p/pTK8KviJHLD
