### ISSUE TITLE
panic when generating client

### ISSUE THREAD

**Issue by 0xmohit** [go-swagger/go-swagger#1874]
## Problem statement
`swagger generate client` panic.

## Swagger specification
https://github.com/stripe/openapi/blob/master/openapi/spec2.json?raw=true

## Steps to reproduce
```
swagger generate client -f "https://github.com/stripe/openapi/blob/master/openapi/spec2.json?raw=true" -A stripe -t src/stripe --skip-validation
```

It results in:

```
2019/02/05 20:49:11 preprocessing spec with option:  minimal flattening
2019/02/05 20:49:11 building a plan for generation
2019/02/05 20:49:11 planning definitions
2019/02/05 20:49:17 planning operations
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe pc=0xa5682a]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).NewSliceBranch(0xc006408000, 0xc004735680, 0x1)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:459 +0x1da
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildArray(0xc006408000, 0x0, 0x0)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1383 +0x141
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildItems(0xc006408000, 0x0, 0x0)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1458 +0x1002
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc006408000, 0x44, 0xc004735680)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1946 +0xe89
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildArray(0xc006408000, 0x0, 0x0)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1379 +0x894
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildItems(0xc006408000, 0x0, 0x0)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1458 +0x1002
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc006408000, 0xc00129e9e0, 0x11)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1946 +0xe89
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildProperties(0xc00507a000, 0x4a, 0xc005747800)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:738 +0x6e4
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc00507a000, 0xc003841200, 0x9)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1934 +0xdc9
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).buildProperties(0xc0021a2600, 0x4a, 0xc0057492d0)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:719 +0x151c
github.com/go-swagger/go-swagger/generator.(*schemaGenContext).makeGenSchema(0xc0021a2600, 0xc00225cb90, 0xc003577680)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/model.go:1934 +0xdc9
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).buildOperationSchema(0xc00574e3f0, 0xc003841200, 0x9, 0xc0072f19a0, 0x15, 0xc0038417b0, 0xf, 0xc5367d, 0x1, 0xc53679, ...)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/operation.go:1086 +0x20d
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).MakeBodyParameter(0xc00574e3f0, 0xc00574b180, 0xc00225cb90, 0xc003577680, 0x2, 0xc003841210)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/operation.go:785 +0x204
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).MakeParameter(0xc00574e3f0, 0xc5367d, 0x1, 0xc00225cb90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/operation.go:748 +0xee4
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).MakeOperation(0xc00574e3f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/operation.go:354 +0xe65
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc005751ad0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/support.go:618 +0x1377
github.com/go-swagger/go-swagger/generator.(*clientGenerator).Generate(0xc005751ad0, 0xbab89d, 0x6)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/client.go:123 +0xb8
github.com/go-swagger/go-swagger/generator.GenerateClient(0x7ffe05e56805, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002d8200, 0xc10640, ...)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/generator/client.go:115 +0x74b
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).generate(0xc000468900, 0xc0002d8200, 0x0, 0x0)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:72 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0xd85fc0, 0xc000468900, 0x81a901, 0x7f764db982b8)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/shared.go:157 +0x1b1
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Client).Execute(0xc000468900, 0xc0000af830, 0x0, 0x9, 0xc000468900, 0x1)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/client.go:91 +0x37
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000190f00, 0xc00001e0b0, 0x9, 0x9, 0x40dac8, 0x30, 0xc023a0, 0xc0000aeb40, 0xc000473900)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x80b
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc000190f00, 0x6, 0xc57cff, 0x6, 0x0, 0xc9163e)
	/home/mohit/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/home/mohit/go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:140 +0xb68
```

## Environment
swagger version: dev (commit 23af561e4ef0a4851452cf5a98bee8f87a8d0cd1)  
go version: go1.11.4 linux/amd64
OS: Linux

**Comment by fredbi** [comment]
The spec is invalid. Please run `swagger validate` first.
The `--skip-validation` only allows for a bit of of tolerance, but then you may panic the generator.

**Comment by 0xmohit** [comment]
[swagger-validator](https://hub.docker.com/r/swaggerapi/swagger-validator) doesn't complain of any errors in the spec.

**Comment by fredbi** [comment]
Results from checking your spec: `swagger validate {your spec}`
[validate.txt](https://github.com/go-swagger/go-swagger/files/2850328/validate.txt)

**Comment by 0xmohit** [comment]
The spec is invalid; closing this.
