### ISSUE TITLE
swagger generate server exception

### ISSUE THREAD

**Issue by lukekhamilton** [go-swagger/go-swagger#1882]
## Problem statement

When running the below swagger generate server command on the pet store demo contract I am getting an unexpected exception.

```
swagger generate server -f swagger_pet_store.json
```

Error:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16037e5]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports.(*pass).importIdentifier(...)
	/go/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports/fix.go:307
github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports.(*pass).load(0xc00139d480, 0xc00139d480)
	/go/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports/fix.go:339 +0x525
github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports.fixImportsDefault(0xc001a75100, 0xc000bd0f80, 0xc001b1f560, 0x17, 0xd63, 0x1346)
	/go/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports/fix.go:504 +0x2f9
github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports.Process(0xc001b1f560, 0x17, 0xc0002b2000, 0xd63, 0x1346, 0xc0016a02c0, 0xc001b1e493, 0x4, 0xc0016a02f8, 0x10981e1, ...)
	/go/src/github.com/go-swagger/go-swagger/vendor/golang.org/x/tools/imports/imports.go:66 +0x72b
github.com/go-swagger/go-swagger/generator.GoLangOpts.func1(0xc001b1f560, 0x17, 0xc0002b2000, 0xd63, 0x1346, 0xc0016a0338, 0x1090f75, 0x0, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/generator/shared.go:196 +0x99
github.com/go-swagger/go-swagger/generator.(*LanguageOpts).FormatContent(0xc000030100, 0xc001b1f560, 0x17, 0xc0002b2000, 0xd63, 0x1346, 0x1346, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/shared.go:117 +0x6f
github.com/go-swagger/go-swagger/generator.(*GenOpts).write(0xc0002fa200, 0xc0016a0700, 0x1727ea0, 0xc001d9ef00, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/generator/shared.go:835 +0x6e0
github.com/go-swagger/go-swagger/generator.(*GenOpts).renderOperation(0xc0002fa200, 0xc001d9ef00, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/generator/shared.go:908 +0x225
github.com/go-swagger/go-swagger/generator.(*appGenerator).Generate(0xc0004bef00, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:237 +0x382
github.com/go-swagger/go-swagger/generator.GenerateServer(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002fa200, 0x180aa80, ...)
	/go/src/github.com/go-swagger/go-swagger/generator/support.go:44 +0xcb
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).generate(0xc00015a4e0, 0xc0002fa200, 0x0, 0x0)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:90 +0x94
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0x1980160, 0xc00015a4e0, 0x141c301, 0x25b00c0)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/shared.go:157 +0x1b1
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc00015a4e0, 0xc00011a360, 0x0, 0x6, 0xc00015a4e0, 0x1)
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:114 +0x37
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc000083f80, 0xc0000aa010, 0x6, 0x6, 0x100bd38, 0x30, 0x17fc920, 0xc0000c8ab0, 0xc00045d100)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:316 +0x80b
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc000083f80, 0x6, 0x18525e7, 0x6, 0x0, 0x188bb64)
	/go/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:186 +0x71
main.main()
	/go/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:140 +0xb68
make: *** [Makefile:12: generate_server] Error 2

```

Please remove the sections that don't apply

## Swagger specification
2.0
## Steps to reproduce
```
git clone https://github.com/lukekhamilton/go-swagger-bug
cd go-swagger-bug
make generate_server
```
## Environment
swagger version: 
```
version: v0.18.0
commit: 6b23bb61413826ce42c3b14a37bf5870caf91e0b  
```
go version: ```go version go1.11.5 darwin/amd64```
OS:   ```OSX Mojace 10.14.3```
uname -a: 
```
Darwin ShinyApple.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64 i386 MacBookPro15,2 Darwin
```

**Comment by lukekhamilton** [comment]
Also this is a binary distribution of swagger via homebrew. 

```
lrwxr-xr-x 1 metta 39 Feb 13 09:55 /usr/local/bin/swagger -> ../Cellar/go-swagger/0.18.0/bin/swagger*
```
```
 brew info go-swagger
go-swagger/go-swagger/go-swagger: stable 0.18.0
Toolkit to work with swagger for golang
https://github.com/go-swagger/go-swagger
/usr/local/Cellar/go-swagger/0.18.0 (3 files, 16MB) *
  Built from source on 2019-02-13 at 09:55:21
From: https://github.com/go-swagger/homebrew-go-swagger/blob/master/go-swagger.rb
==> Options
--with-goswagger
	Names the binary goswagger instead of swagger
```

**Comment by fredbi** [comment]
Looks very much like a GOPATH issue with the go import tool.
Maybe setting a generation target inside GOPATH would help?

**Comment by lukekhamilton** [comment]
just tested the generate process within the $GOPATH and it works. However according to the doco it should work with go modules too. So I still think this is a bug. At least with a workaround.

**Comment by fredbi** [comment]
It works with go modules, but not with arbitrary module location.
Our issue here is dealing with the `goimport` tool, which does not support this yet.

**Comment by lukekhamilton** [comment]
Not 100% sure what you mean by `arbitrary module location`? Maybe you can tell me how I could get this to work with with go modules? This would be really appreciated.

**Comment by casualjim** [comment]
when the go toolchain is fixed, our project will be fixed.  This is a problem in the go toolchain itself.
go 1.11 calls module experimental because they didn't have it fully integrated into everything.

The goimports tool, which we depend upon and what is failing for you, doesn't work outside of the gopath. It might be that it got fixed since our last release then it will get picked up with our next release.

One possible way you go modules oustide of the gopath (arbitrary module location), is by cheating

make a file called run-in-gopath

```sh
#!/bin/bash

set -eu

dir=$(git rev-parse --show-toplevel)
cd "$dir"
echo "Syncing vendor..."
go mod vendor
trap "rm -rf vendor" EXIT

docker run \
  --rm \
  -i \
  --user $(id -u) \
  -v "$dir":/go/src/github.com/org/project \
  -w /go/src/github.com/org/project \
  quay.io/goswagger/swagger "$@"
```

then you can run your generation with: `./run-in-gopath swagger generate server`

**Comment by fredbi** [comment]
@lukekhamilton  we are monitoring toolchain support progress here, in case you are interested:
https://github.com/golang/go/issues/24661

**Comment by lukekhamilton** [comment]
Hey guys, 
As of: `go version go1.12 darwin/amd64`

This is now working for me with go modules. Woohoo

**Comment by mllrjb** [comment]
@lukekhamilton - I wasn't able to get this to work with go modules directly, but using the Netlify approach mentioned [here](https://github.com/go-swagger/go-swagger/issues/1724#issuecomment-469335593) did work for me. 

Were you able to get it working directly? I ran into issues with my `auth` package not resolving an import in generated code.

**Comment by fredbi** [comment]
Generate spec should just work with modules now. Closing.
