### ISSUE TITLE
Server crashes when polymorphic value is absent in post body

### ISSUE THREAD

**Issue by ribaptista** [go-swagger/go-swagger#1993]
## Problem statement
Generated server crashes when one posts an entity missing a required polymorphic value

## Swagger specification
```yaml
consumes:
- application/json
info:
  title: Pets
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
definitions:
  House:
    type: object
    properties:
      pet:
        $ref: '#/definitions/Pet'
    required:
    - pet
  Pet:
    type: object
    discriminator: petType
    properties:
      name:
        type: string
      petType:
        type: string
    required:
    - name
    - petType
  Dog:
    type: object
    description: A representation of a dog
    allOf:
    - $ref: '#/definitions/Pet'
    - properties:
        packSize:
          type: integer
          format: int32
          description: the size of the pack the dog is from
          default: 0
          minimum: 0
      required:
      - packSize
paths:
  "/houses":
    post:
      summary: Creates a house
      produces:
        - application/json
      operationId: postHouse
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/House"
      responses:
        '200':
          description: House response
        default:
          description: unexpected error
```
### Build
```
go mod init pets
swagger generate server
go build ./cmd/pets-server/
./pets-server --port 3000
```
### Failing test (missing polymorphic property `pet`)
```
$ curl -X POST http://127.0.0.1:3000/houses -H 'Content-Type: application/json' -d '{}'
curl: (52) Empty reply from server
```
### Server stdout
```
2019/07/03 15:01:15 Serving pets at http://127.0.0.1:3000
2019/07/03 15:01:18 http: panic serving 127.0.0.1:59002: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc0002ee000)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x8ef580, 0xd763f0)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
pipeline/models.(*House).validatePet(0xc000495840, 0xa1ab40, 0xc000153260, 0x938d00, 0xc000495840)
	/projects/tmp/swagger-discriminator/models/house.go:104 +0x29
pipeline/models.(*House).Validate(0xc000495840, 0xa1ab40, 0xc000153260, 0x938d00, 0xc000495840)
	/projects/tmp/swagger-discriminator/models/house.go:92 +0x4f
pipeline/restapi/operations.(*PostHouseParams).BindRequest(0xc000495800, 0xc000514a00, 0xc000514900, 0x0, 0x0)
	/projects/tmp/swagger-discriminator/restapi/operations/post_house_parameters.go:56 +0x3dd
github.com/go-openapi/runtime/middleware.(*Context).BindValidRequest(0xc000493260, 0xc000514a00, 0xc000514900, 0xa15060, 0xc000495800, 0x8bfc01, 0xa194a0)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.2/middleware/context.go:317 +0x23a
pipeline/restapi/operations.(*PostHouse).ServeHTTP(0xc000496260, 0xa18ce0, 0xc000108540, 0xc000514a00)
	/projects/tmp/swagger-discriminator/restapi/operations/post_house.go:49 +0xba
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0xa18ce0, 0xc000108540, 0xc000514a00)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.2/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc000494720, 0xa18ce0, 0xc000108540, 0xc000514a00)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0xa18ce0, 0xc000108540, 0xc0002f2300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.2/middleware/router.go:76 +0x358
net/http.HandlerFunc.ServeHTTP(0xc00046a300, 0xa18ce0, 0xc000108540, 0xc0002f2300)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0xa18ce0, 0xc000108540, 0xc0002f2300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.2/middleware/redoc.go:72 +0x94
net/http.HandlerFunc.ServeHTTP(0xc000065c80, 0xa18ce0, 0xc000108540, 0xc0002f2300)
	/usr/local/go/src/net/http/server.go:1964 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0xa18ce0, 0xc000108540, 0xc0002f2300)
	/go/pkg/mod/github.com/go-openapi/runtime@v0.19.2/middleware/spec.go:46 +0x73
net/http.HandlerFunc.ServeHTTP(0xc000065cc0, 0xa18ce0, 0xc000108540, 0xc0002f2300)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.serverHandler.ServeHTTP(0xc000270000, 0xa18ce0, 0xc000108540, 0xc0002f2300)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0002ee000, 0xa193e0, 0xc000283400)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```
### Passing test (containing required property `pet`)
```
$ curl -X POST http://127.0.0.1:3000/houses -H 'Content-Type: application/json' -d '{"pet": {"petType": "Dog", "name": "Doggo", "packSize": 10 }}}'
"operation PostHouse has not yet been implemented"
```
## Environment
swagger version: 0.19.0
go version: 1.11.5  
OS: Linux version 4.9.125-linuxkit (root@659b6d51c354) (gcc version 6.4.0 (Alpine 6.4.0) ) #1 SMP Fri Sep 7 08:20:28 UTC 2018

**Comment by fredbi** [comment]
Yes it looks like the required check / non-required guard  is not generated when it comes to base type...
