### ISSUE TITLE
Delete requests with bodies cause a runtime error

### ISSUE THREAD

**Issue by cozmo** [go-swagger/go-swagger#219]
Using the following swagger.yml

```yml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'delete-body-api'
paths:
  /path:
    delete:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Delete an object
      parameters:
        - name: body
          in: body
          description: this argument is an object with a string key
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
      responses:
        '200':
          description: All is good
```
You can successfully validate, generate, and run a server. That said when trying to make a request

```
curl -H "Content-Type: application/json" -X DELETE -d '{}' http://localhost:8000/path
```

You get a runtime exception - 

```
2016/01/20 13:39:01 http: panic serving 127.0.0.1:51765: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc8201e2000, 0x7bda80, 0xc8201e0000)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1287 +0xb5
github.com/Clever/swagger-test/restapi/operations.(*DeletePathParams).BindRequest(0xc820232608, 0xc82032a000, 0xc82032a0e0, 0x0, 0x0)
	/Users/templaedhel/go/src/github.com/Clever/swagger-test/restapi/operations/delete_path_parameters.go:37 +0x122
github.com/go-swagger/go-swagger/httpkit/middleware.(*Context).BindValidRequest(0xc820141640, 0xc82032a000, 0xc82032a0e0, 0x7bdc60, 0xc820232608, 0x0, 0x0)
	/Users/templaedhel/go/src/github.com/go-swagger/go-swagger/httpkit/middleware/context.go:234 +0x328
github.com/Clever/swagger-test/restapi/operations.(*DeletePath).ServeHTTP(0xc820232600, 0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/Users/templaedhel/go/src/github.com/Clever/swagger-test/restapi/operations/delete_path.go:48 +0x101
github.com/go-swagger/go-swagger/httpkit/middleware.newOperationExecutor.func1(0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/Users/templaedhel/go/src/github.com/go-swagger/go-swagger/httpkit/middleware/operation.go:23 +0x6f
net/http.HandlerFunc.ServeHTTP(0xc82018f9c0, 0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/go-swagger/go-swagger/httpkit/middleware.newRouter.func1(0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/Users/templaedhel/go/src/github.com/go-swagger/go-swagger/httpkit/middleware/router.go:78 +0x108
net/http.HandlerFunc.ServeHTTP(0xc820141980, 0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
github.com/go-swagger/go-swagger/httpkit/middleware.specMiddleware.func1(0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/Users/templaedhel/go/src/github.com/go-swagger/go-swagger/httpkit/middleware/spec.go:36 +0x1d1
net/http.HandlerFunc.ServeHTTP(0xc8202af5c0, 0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1422 +0x3a
net/http.serverHandler.ServeHTTP(0xc8200147e0, 0x7bdc28, 0xc8201e20b0, 0xc82032a000)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1862 +0x19e
net/http.(*conn).serve(0xc8201e2000)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.5.1/libexec/src/net/http/server.go:1910 +0x3f6
```

As I see it there are a few possibilities here:

1. Fix the code causing the runtime exception. My understanding is that should be as simple as adding delete [here](https://github.com/go-swagger/go-swagger/blob/master/httpkit/request.go#L28)
2. Decide that we don't want to support DELETEs with bodies. Generally you shouldn't be sending bodies with REST APIs, _but_ it isn't forbidden in HTTP1.1 - http://tools.ietf.org/html/rfc7231#section-4.3.5. If this is the case it should probably fail validation. 

Happy to submit a PR but would like to hear thoughts on which approach we want to take here.

**Comment by casualjim** [comment]
Excellent question!

Personally I'd err on making it not panic (although I think you'll find a comment about a panic middleware should handle this), but also not allowing bodies in DELETE.

I can however come up with a use case for it that makes sense. Let's say your a search engine of some sort and you want to allow for a query document to govern the selection for what needs to get deleted. In that case the body would make a lot of sense. So contrary to what I want out of principle my vote goes to option 1.
