### ISSUE TITLE
Error route panics with a string parameter.

### ISSUE THREAD

**Issue by kreativka** [go-swagger/go-swagger#2275]
## Problem statement

Error route panics with a string parameter. Should return "Bad request".

---
curl localhost:53941/pets/123/list
curl: (52) Empty reply from server
----

http: panic serving 127.0.0.1:54520: Bad request (string) is not supported by the ByteStreamProducer, can be resolved by supporting Reader/BinaryMarshaler interface
goroutine 15 [running]:net/http.(*conn).serve.func1(0xc0001232c0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:1772 +0x139
panic(0x1567c80, 0xc00048e660)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:975 +0x3e3
pets/server/restapi/operations/pets.(*GetPetsBadRequest).WriteResponse(0xc00048e560, 0x16ed680, 0xc0000bc2a0, 0x16e39e0, 0xc000523fc0)
	/Users/asd/cup/petIssue/server/restapi/operations/pets/get_pets_responses.go:95 +0xfb
github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc00044ec60, 0x16ed680, 0xc0000bc2a0, 0xc000090b00, 0xc000526180, 0x2, 0x2, 0xc000090900, 0x1585bc0, 0xc00048e560)
	/Users/asd/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/context.go:506 +0x56b
pets/server/restapi/operations/pets.(*GetPets).ServeHTTP(0xc0004afde0, 0x16ed680, 0xc0000bc2a0, 0xc000090a00)
	/Users/asd/cup/petIssue/server/restapi/operations/pets/get_pets.go:56 +0x24d
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0x16ed680, 0xc0000bc2a0, 0xc000090a00)
	/Users/asd/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/operation.go:28 +0x75
net/http.HandlerFunc.ServeHTTP(0xc000523ff0, 0x16ed680, 0xc0000bc2a0, 0xc000090a00)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2012 +0x44
github.com/go-openapi/runtime/middleware.NewRouter.func1(0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/Users/asd/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/router.go:77 +0x356
net/http.HandlerFunc.ServeHTTP(0xc000527cc0, 0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2012 +0x44
github.com/go-openapi/runtime/middleware.Redoc.func1(0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/Users/asd/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/redoc.go:72 +0x286
net/http.HandlerFunc.ServeHTTP(0xc00007d3c0, 0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2012 +0x44
github.com/go-openapi/runtime/middleware.Spec.func1(0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/Users/asd/go/pkg/mod/github.com/go-openapi/runtime@v0.19.15/middleware/spec.go:46 +0x188
net/http.HandlerFunc.ServeHTTP(0xc00007d440, 0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2012 +0x44
net/http.serverHandler.ServeHTTP(0xc0004b8000, 0x16ed680, 0xc0000bc2a0, 0xc000090800)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0001232c0, 0x16eec80, 0xc00007d540)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2933 +0x35c

## Swagger specification

swagger: "2.0"
info:
  title: Pets
  description: Lists pets
  version: "0.1"
schemes:
- http
produces:
- application/json
consumes:
- application/json
parameters:
 path_petID:
    in: path
    name: petID
    type: string
    required: true
    description: ID of the pet
paths:
  /pets/{petID}/list:
    get:
      tags: [ pets ]
      operationId: getPets
      summary: Get pets
      parameters:
        - $ref: "#/parameters/path_petID"
        - in: query
          name: format
          type: string
          enum: [csv, pdf]
          default: csv
          description: Which format to get.
      produces:
        - application/pdf
        - text/csv
      responses:
        200:
          description: PDF or CSV list of pets
          schema:
            type: file
        400:
          description: Bad request
          schema:
            type: string

## Steps to reproduce

		api.PetsGetPetsHandler = pets.GetPetsHandlerFunc(func(params pets.GetPetsParams) middleware.Responder {
			return pets.NewGetPetsBadRequest().WithPayload("Bad request")
		})

## Environment
swagger version: 0.23.0 
go version: 1.13.x 1.14.x
OS:   
macos 10.15.4
Fedora 31/32

**Comment by fredbi** [comment]
Yes I could reproduce your testcase.
The panic is explictly triggered by the server code below. This is because you don't provide the `produce` mime that corresponds to your data (in that case, a string).

Even when we add the extra `application/json` producer, the default chosen one if binary.

```go
// WriteResponse to the client
func (o *GetPetsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
	    panic(err) // let the recovery middleware deal with this    #### your panic ####
	}
}
```

**Comment by fredbi** [comment]
Fix N°1: add explicit support for `application/json` as a possible mime for your responses (the spec at the operation level is an override, not an addition)
```yaml
paths:
  /pets/{petID}/list:
    get:
      tags: [ pets ]
      operationId: getPets
      summary: Get pets
      parameters:
        - $ref: "#/parameters/path_petID"
        - in: query
          name: format
          type: string
          enum: [csv, pdf]
          default: csv
          description: Which format to get.
      produces:
        - application/pdf
        - text/csv
        - application/json
```

**Comment by fredbi** [comment]
Fix N°2 (most important):
Implement the responder override to switch to json when the response is an error.
Example in `configure_pets.go`:
```go
type ForceJSONResponder struct {
	middleware.Responder
}

func (r ForceJSONResponder) WriteResponse(rw http.ResponseWriter, _ runtime.Producer) {
	r.Responder.WriteResponse(rw, runtime.JSONProducer())
}
```
```go
func configureAPI(api *operations.PetsAPI) http.Handler {
       ....
	api.PetsGetPetsHandler = pets.GetPetsHandlerFunc(func(params pets.GetPetsParams) middleware.Responder {
		//return middleware.NotImplemented("operation pets.GetPets has not yet been implemented")
		return ForceJSONResponder{Responder: pets.NewGetPetsBadRequest().WithPayload("Bad request")}
	})
       ...
```

**Comment by fredbi** [comment]
And this works:
```
./pets-server
2020/06/30 02:32:54 Serving pets at http://127.0.0.1:44187
```

```
curl --verbose --header "Content-Type: application/json" http://localhost:44187/pets/123/list
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 44187 (#0)
> GET /pets/123/list HTTP/1.1
> Host: localhost:44187
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 400 Bad Request
< Content-Type: application/pdf
< Date: Tue, 30 Jun 2020 00:33:05 GMT
< Content-Length: 14
< 
"Bad request"
* Connection #0 to host localhost left intact
```

**Comment by fredbi** [comment]
Now you may use some additional runtime utilities to renegotiate the content.
Let's assume we have added support for an extra "application/text" mime in the spec for this response.
So now we may override with the mime of the response negotiated against the client's "Accept" header:
```go

	api.PetsGetPetsHandler = pets.GetPetsHandlerFunc(func(params pets.GetPetsParams) middleware.Responder {
		return middleware.ResponderFunc(func(rw http.ResponseWriter, _ runtime.Producer) {
			mime := middleware.NegotiateContentType(params.HTTPRequest, []string{"application/json", "application/text"}, "application/json")
			var producer runtime.Producer
			switch mime {
			case "application/text":
				producer = runtime.TextProducer()
			default:
				producer = runtime.JSONProducer()
			}
			rw.Header().Set("Content-Type", mime)
			pets.NewGetPetsBadRequest().
				WithPayload("Bad request").
				WriteResponse(rw, producer)
		})
	})
```
Example:
```
 curl --verbose  --header "Accept: application/text" http://localhost:43327/pets/123/list
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 43327 (#0)
> GET /pets/123/list HTTP/1.1
> Host: localhost:43327
> User-Agent: curl/7.58.0
> Accept: application/text
> 
< HTTP/1.1 400 Bad Request
< Content-Type: application/text
< Date: Tue, 30 Jun 2020 06:43:15 GMT
< Content-Length: 11
< 
* Connection #0 to host localhost left intact
```
