### ISSUE TITLE
swagger serve openapi apidocs failed

### ISSUE THREAD

**Issue by hitzhangjie** [go-swagger/go-swagger#2463]
## Problem statement

I have a tool generating apidocs in openapi 3.0.0 spec.

this swagger cmd tool cannot validate it, it reports error like this:

```
Something went wrong...
Document must be valid OpenAPI 3.0.0 definition
Stack trace
Error: Document must be valid OpenAPI 3.0.0 definition
    at e.validate (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:94:21351)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:94:21125)
    at new zi (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:94:25033)
    at new e (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:94:83681)
    at t.makeStore (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:88:66414)
    at t.render (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:88:67362)
    at Fa (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:64:69876)
    at Da (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:64:69671)
    at gs (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:64:105470)
    at cl (https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js:64:96717)

ReDoc Version: 2.0.0-rc.45
Commit: aa53416d
```

But the swagger editor online can validate it.

## Swagger specification

openapi 3.0.x

## Steps to reproduce

swagger serve apidocs.openapi.json

file: apidocs.openapi.json

```
{
 "openapi": "3.0.2",
 "info": {
  "title": "pb",
  "description": "The api document of `hellox.proto`",
  "version": "3.0"
 },
 "paths": {
  "/trpc.app.hello.hello_service/Hello": {
   "post": {
    "summary": "Hello",
    "operationId": "_trpc_app_hello_hello_service_Hello",
    "responses": {
     "200": {
      "description": "",
      "content": {
       "application/json": {
        "schema": {
         "$ref": "#/components/schemas/trpc.app.hello.HelloRsp"
        }
       }
      }
     }
    },
    "requestBody": {
     "content": {
      "application/json": {
       "schema": {
        "$ref": "#/components/schemas/trpc.app.hello.HelloReq"
       }
      }
     }
    },
    "tags": [
     "hello_service"
    ]
   }
  }
 },
 "components": {
  "schemas": {
   "trpc.app.hello.HelloReq": {
    "type": "object",
    "properties": {
     "msg": {
      "type": "string"
     }
    }
   },
   "trpc.app.hello.HelloRsp": {
    "type": "object",
    "properties": {}
   }
  }
 }
}

```

## Environment
swagger version: dev
go version: 1.14
OS:   macOS bigsur

**Comment by casualjim** [comment]
we don't support openapi 3.0
The error seems to come from redoc: https://github.com/Redocly/redoc

**Comment by iselind** [comment]
Are there any plans on when support for oas30 will be added?
