### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by r1se** [go-swagger/go-swagger#2527]
## Problem statement
```
swagger generate model --spec=/home/dvp/go/src/test/api/openapi/v1/swagger.yml 
2021/03/03 15:45:02 validating spec /home/dvp/go/src/test/api/openapi/v1/swagger.yml
2021/03/03 15:45:03 preprocessing spec with option:  minimal flattening
2021/03/03 15:45:03 building a plan for generation
2021/03/03 15:45:03 generation target ./
2021/03/03 15:45:03 planning definitions (found: 5)
2021/03/03 15:45:03 planning operations (found: 5)
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.paramMappings(0xc000748660, 0xd9a41b, 0x3, 0xc001ebe3d0)
        /app/generator/operation.go:259 +0x91c
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).MakeOperation(0xc001f79d40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/generator/operation.go:324 +0x2ef
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc000f0db00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/generator/support.go:339 +0x12b0
github.com/go-swagger/go-swagger/generator.(*appGenerator).Generate(0xc000f0db00, 0x0, 0x0)
        /app/generator/support.go:150 +0xa5
github.com/go-swagger/go-swagger/generator.GenerateModels(0x0, 0x0, 0x0, 0xc0001f4c80, 0x0, 0x0)
        /app/generator/model.go:63 +0xdc
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Model).generate(0xc00031de60, 0xc0001f4c80, 0x0, 0x0)
        /app/cmd/swagger/commands/generate/model.go:85 +0xd8
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.createSwagger(0xee6140, 0xc00031de60, 0x0, 0x7fb5f369b298)
        /app/cmd/swagger/commands/generate/shared.go:184 +0x22d
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Model).Execute(0xc00031de60, 0xc00041ee10, 0x0, 0x3, 0xc00031de60, 0x1)
        /app/cmd/swagger/commands/generate/model.go:98 +0xe5
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0003155c0, 0xc000032090, 0x3, 0x3, 0x10, 0xddcf70, 0x2a, 0xc690e0, 0xc0003215c0)
        /go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x89b
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /go/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
        /app/cmd/swagger/swagger.go:137 +0xb65

```

## Environment
swagger version: 0.26.1 
go version: 1.15.8
OS: Ubuntu 18.04   

[swagger.zip](https://github.com/go-swagger/go-swagger/files/6077224/swagger.zip)

**Comment by fredbi** [comment]
Most likely similar to #2511

**Comment by lastchiliarch** [comment]
Can I have a try?

**Comment by r1se** [comment]
@fredbi i'm use debugging, and see problem in mapping, when paths/parametrs it's ref on some definitions. In my case
- $ref: '#/definitions/Exchange'

On code:
go-swagger/generator/operation.go line 253, we don't have p.Name if use ref

**Comment by fredbi** [comment]
ok so digging into that one again.

1. First problem, the spec is invalid (the parameter pointed to by the $ref misses both name and in) and the validation doesn't detect it: on the surface, a parameter may be a $ref and the validate method doesn't check further
2. Second problem, the panicking should be guarded - it is okay to try codegen with some tolerance, but we should avoid panic nonetheless
