### ISSUE TITLE
Panic on parsing interface type definition

### ISSUE THREAD

**Issue by Pungyeon** [go-swagger/go-swagger#2588]
## Problem statement

Please remove the sections that don't apply

## Swagger specification
`N/A`

## Steps to reproduce
Create an `interface` and then create a type definition, which embeds this `interface`. Finally, create a `struct` which contains this new type definition, which is parsed by go-swagger.

Example:
```go 
type A interface {
  Do()
}

type B A

type C struct {
  B
}
```

Using the swagger command: 

```
swagger generate spec -m -i swagger.yaml -o swagger.json
```

will result in a panic, which the following output:

```
panic: interface conversion: ast.Expr is *ast.Ident, not *ast.InterfaceType

goroutine 1 [running]:
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromInterface(0xc06e0b1980, 0xc0765ca900, 0xc060e08460, 0xc0765cc900, 0xc06e0b10d8, 0xc0765ca900, 0xc0648a6001)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/schema.go:408 +0x1f14
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildEmbedded(0xc06e0b1980, 0x1b218c0, 0xc060e154a0, 0xc0765cc900, 0xc06e0b10d8, 0x30, 0xc06e0b0610)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/schema.go:849 +0x4e5
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromInterface(0xc06e0b1980, 0xc071ba9480, 0xc060e15450, 0xc0765cc6c0, 0xc06e0b10d8, 0x10, 0xc076531d30)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/schema.go:449 +0x9ed
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromType(0xc06e0b1980, 0x1b21840, 0xc060e15450, 0x1b34780, 0xc076531d60, 0x0, 0x0)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/schema.go:235 +0x8cf
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromDecl(0xc06e0b1980, 0xc071ba9480, 0xc0765cc6c0, 0x2126da0, 0x6)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/schema.go:205 +0xdba
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).Build(0xc06e0b1980, 0xc0629c2330, 0x1, 0x299)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/schema.go:150 +0xcc
github.com/go-swagger/go-swagger/codescan.(*specBuilder).buildDiscoveredSchema(0xc06352ab90, 0xc071ba9480, 0x0, 0x0)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/spec.go:114 +0xd5
github.com/go-swagger/go-swagger/codescan.(*specBuilder).joinExtraModels(0xc06352ab90, 0xc06305f1c0, 0x0)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/spec.go:218 +0x28c
github.com/go-swagger/go-swagger/codescan.(*specBuilder).buildModels(0xc06352ab90, 0xc06352ab90, 0xc0629c23c0)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/spec.go:205 +0x100
github.com/go-swagger/go-swagger/codescan.(*specBuilder).Build(0xc06352ab90, 0xc063696b40, 0x1, 0xc06352ab90)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/spec.go:49 +0x2f
github.com/go-swagger/go-swagger/codescan.Run(0xc06a969c80, 0xc, 0x0, 0x0)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/codescan/application.go:77 +0x83
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*SpecFile).Execute(0xc0000b2b00, 0xc00024da40, 0x1, 0x1, 0xc0000b2b00, 0x1)
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/cmd/swagger/commands/generate/spec_go111.go:57 +0x1d1
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0001e8bd0, 0xc000032090, 0x7, 0x7, 0x10, 0x19c5e6b, 0x2a, 0x183eb20, 0xc0001c6b80)
        /Users/lmj/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:335 +0x8c3
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /Users/lmj/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
        /Users/lmj/go/pkg/mod/github.com/go-swagger/go-swagger@v0.27.0/cmd/swagger/swagger.go:140 +0xc07
```

## Environment
swagger version: 2.7.0  
go version: 1.14
OS:  darwin (Mac OS X Catalina 10.15.7)

**Comment by Pungyeon** [comment]
I would like to add, that fixing this is fairly easy. If you simply to add the following type assertion check to `./codescan/schema.go::407`, everything works as intended 👍 

```go
var flist []*ast.Field
if _, ok := decl.Spec.Type.(*ast.InterfaceType); ok {
	flist := make([]*ast.Field, it.NumEmbeddeds()+it.NumExplicitMethods())
	for i := range decl.Spec.Type.(*ast.InterfaceType).Methods.List {
		flist[i] = decl.Spec.Type.(*ast.InterfaceType).Methods.List[i]
	}
}
```

**Comment by casualjim** [comment]
can you make a PR with this change, I think you are looking at a different version of the code. I think this must be at line 423
