### ISSUE TITLE
v0.30.4 panics during flatten

### ISSUE THREAD

**Issue by andrewpmartinez** [go-swagger/go-swagger#2919]
## Problem statement

A OAS2.0 spec that flattens multiple files fine in v0.28.0 and v0.29.0, but panics in v0.30.4.

```
> swagger flatten .\client.yml -o ..\client.yml --format yaml
2023/04/03 13:32:27 format =  yaml
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x833f51]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc0005598d0)
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:294 +0x6d
panic({0xd6cbe0, 0x14e4930})
        /opt/hostedtoolcache/go/1.19.5/x64/src/runtime/panic.go:884 +0x212
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00?, 0xc000eebe00?, {0x0?, 0x0?})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:434 +0x31
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000eeb4a0, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000eeb400, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000eeb360, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000eeaf00, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000ee7400, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000ee70e0, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc00033d4a0, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc0004e9860, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc0006f1e00, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:526 +0x11e5
gopkg.in/yaml%2ev3.(*encoder).node(0xc000c80c00, 0xc000402000, {0x0, 0x0})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:477 +0x1685
gopkg.in/yaml%2ev3.(*encoder).nodev(0xdcdb40?, {0xdcdb40?, 0xc000402000?, 0x30001?})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:429 +0x53
gopkg.in/yaml%2ev3.(*encoder).marshalDoc(0xc000c80c00, {0x0, 0x0}, {0xdcdb40?, 0xc000402000?, 0x0?})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/encode.go:101 +0xc5
gopkg.in/yaml%2ev3.Marshal({0xdcdb40?, 0xc000402000})
        /home/runner/go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/yaml.go:222 +0x389
github.com/go-openapi/swag.JSONMapSlice.MarshalYAML({0xc0006b0400, 0xa, 0x1a000?})
        /home/runner/go/pkg/mod/github.com/go-openapi/swag@v0.22.3/yaml.go:245 +0x131
github.com/go-swagger/go-swagger/cmd/swagger/commands.writeToFile(0xc000913040?, 0x1, {0xc0001260f0?, 0xc?}, {0xc0001260d0, 0xd})
        /home/runner/work/go-swagger/go-swagger/cmd/swagger/commands/expand.go:65 +0x1ba
github.com/go-swagger/go-swagger/cmd/swagger/commands.(*FlattenSpec).Execute(0xc0003fb090, {0xc000188840?, 0xc0003fb090?, 0x6?})
        /home/runner/work/go-swagger/go-swagger/cmd/swagger/commands/flatten.go:47 +0x186
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0001f27e0, {0xc000152010, 0x6, 0x7})
        /home/runner/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:335 +0x8a2
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /home/runner/go/pkg/mod/github.com/jessevdk/go-flags@v1.5.0/parser.go:191
main.main()
        /home/runner/work/go-swagger/go-swagger/cmd/swagger/swagger.go:140 +0x971
```

## Swagger specification

https://github.com/openziti/edge-api/tree/main/source contains a `management.yml` and `client.yml` that needs to be flattened. Used to generate `management.yml` and `client.yml` in the directory above.

## Steps to reproduce

1) clone https://github.com/openziti/edge-api
2) `git checkout f8a274ee0645c2cd27b29bd838916b7b617a8d6a` (should work on main, but this is the commit I was on when the issue present itself)
3) `cd edge-api/source`
4) `swagger flatten .\client.yml -o ..\client.yml --format yaml`

## Environment

Works:

version: v0.28.0
commit: 48a66e4bdbcde02c8c6c95ff9a08f64fe40b1b50

Works:

version: v0.29.0
commit: 09ae1192ca9a941bbb534aca09e6bdc562c95ef3

Panics:

version: v0.30.4
commit: df6da9b77aa9751f06bedb17fcf92b1ab67a7a47

OS:   Windows 11 & Ubuntu 20

**Comment by fredbi** [comment]
Could reproduce this panic.
The validates okay, expands okay, flattens without error but fails when marshaling the YAML sing yaml.v3.

**Comment by fredbi** [comment]
The culprit definition are some empty "cause" fields: there is a bug in swag MarshalYAML that doesn't handle null values correctly. Fixing it.
