### ISSUE TITLE
panic: interface conversion: interface is spec.Schema, not spec.Parameter

### ISSUE THREAD

**Issue by vburenin** [go-swagger/go-swagger#342]
I've made accidental copy paste error in the paths section, that resulted in this stack trace error:

```
2016/02/29 13:59:10 building a plan for generation
2016/02/29 13:59:10 planning definitions
2016/02/29 13:59:10 planning operations
panic: interface conversion: interface is spec.Schema, not spec.Parameter

goroutine 1 [running]:
panic(0x6d97c0, 0xc8206b2dc0)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/go-swagger/go-swagger/spec.(*specAnalyzer).paramsAsMap(0xc82000b7a0, 0xc8206f9400, 0x3, 0x4, 0xc820962390)
    /drone/src/github.com/go-swagger/go-swagger/spec/analyzer.go:331 +0x1c5
github.com/go-swagger/go-swagger/spec.(*specAnalyzer).ParamsFor(0xc82000b7a0, 0x7a9dd0, 0x3, 0xc820011fb0, 0x10, 0x4)
    /drone/src/github.com/go-swagger/go-swagger/spec/analyzer.go:379 +0x1f1
github.com/go-swagger/go-swagger/generator.(*codeGenOpBuilder).MakeOperation(0xc820392d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /drone/src/github.com/go-swagger/go-swagger/generator/operation.go:318 +0x412
github.com/go-swagger/go-swagger/generator.(*appGenerator).makeCodegenApp(0xc8204917a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /drone/src/github.com/go-swagger/go-swagger/generator/support.go:571 +0xf2f
github.com/go-swagger/go-swagger/generator.(*appGenerator).Generate(0xc8204917a0, 0x0, 0x0)
    /drone/src/github.com/go-swagger/go-swagger/generator/support.go:154 +0x87
github.com/go-swagger/go-swagger/generator.GenerateServer(0x7fff5fbffb4b, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7fff5fbffb52, 0xd, ...)
    /drone/src/github.com/go-swagger/go-swagger/generator/support.go:40 +0x118
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*Server).Execute(0xc8201d63c0, 0xc82026be80, 0x0, 0x8, 0x0, 0x0)
    /drone/src/github.com/go-swagger/go-swagger/cmd/swagger/commands/generate/server.go:69 +0x22e
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc8202e2b40, 0xc820088010, 0x8, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
    /drone/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:301 +0xa10
github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags.(*Parser).Parse(0xc8202e2b40, 0x0, 0x0, 0x0, 0x0, 0x0)
    /drone/src/github.com/go-swagger/go-swagger/vendor/github.com/jessevdk/go-flags/parser.go:175 +0x9b
main.main()
    /drone/src/github.com/go-swagger/go-swagger/cmd/swagger/swagger.go:79 +0x841
```

Broken path definition:

> ```
> /get_main_object:
> get:
>   tags:
>     - maindata
>   parameters:
>     - name: sid
>       in: query
>       required: true
>       $ref: "#/definitions/sample_info/properties/sid"  <<<< Error is here.
> ```

```
Go 1.6
Swagger version:  0.4.0
```

**Comment by casualjim** [comment]
* a $ref property takes over that entire object
* a parameter is pointing to a schema you can use a parameters top level property.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields

So if you want to share parameters you can define it in the parameters top level property and do something like:

```
parameters:
  sid:
    in: query
    required: true
    type: integer
    format: int64
/get_main_object:
  get:
    tags:
      - maindata
    parameters:
      - $ref: "#/parameters/sid"
```

**Comment by vburenin** [comment]
It was just a copy/paste error I made that caused crash during the generation process. So, I wanted to point out that there is a place go-swagger panics.

**Comment by casualjim** [comment]
at least for json this could be helpful: https://github.com/ajeddeloh/go-json

**Comment by fredbi** [comment]
Just restested this.
1. No more panic: a validation error is detected. Strangely, errors are repeated.
2. @casualjim : your example is not validated. "Cannot unmarshall object".

I think we can close the "panic" issue and perhaps dedicate a more accurate issue on validation messages relevances.

Preparing a PR with fixtures and UT.
