### ISSUE TITLE
Tips for debugging BindValidRequest() errors?

### ISSUE THREAD

**Issue by SandyWalsh** [go-swagger/go-swagger#773]
## Problem statement
I'm trying to debug an issue with a bad POST handler. The problem seems to stem from `BindValidRequest` in `operations.post_foo.go` during the `o.context.Respond()` call.  

I'd like to find the offending portion of the input data. Or some details on where the input parameter unmarsaling occurs (I looked at `https://github.com/go-swagger/go-swagger/blob/master/design.md` do no avail)

Looking at the stack trace leads me to `go-openapi/middleware/context.go` but no particulars what might be going on. 

```
2016/12/02 17:45:05 http: panic serving 127.0.0.1:35882: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc42074a300)
        /usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x8c9b80, 0xc4200120b0)
        /usr/local/go/src/runtime/panic.go:458 +0x243
code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware.(*Context).Respond(0xc420700980, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0, 0xc420013990, 0x1, 0x1, 0xc42001b180, 0x8ca8a0, 0xc420446600)
        /home/sandy/go/src/code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware/context.go:438 +0x7b1
code.foo.com/MyCo/mosaics-api/server/restapi/operations.(*PostMosaicExperimentalMosaics).ServeHTTP(0xc42031a660, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /home/sandy/go/src/code.foo.com/MyCo/mosaics-api/server/restapi/operations/post_mosaic_experimental_mosaics.go:49 +0x34d
code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1(0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /home/sandy/go/src/code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware/operation.go:24 +0x69
net/http.HandlerFunc.ServeHTTP(0xc420107b50, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware.NewRouter.func1(0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /home/sandy/go/src/code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware/router.go:89 +0x478
net/http.HandlerFunc.ServeHTTP(0xc42078f680, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware.Redoc.func1(0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /home/sandy/go/src/code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware/redoc.go:72 +0xac
net/http.HandlerFunc.ServeHTTP(0xc42078f800, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware.Spec.func1(0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /home/sandy/go/src/code.foo.com/MyCo/mosaics-api/vendor/github.com/go-openapi/runtime/middleware/spec.go:45 +0x8b
net/http.HandlerFunc.ServeHTTP(0xc42078f840, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /usr/local/go/src/net/http/server.go:1726 +0x44
net/http.serverHandler.ServeHTTP(0xc420791980, 0xc0ffa0, 0xc4206de340, 0xc42066e0f0)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42074a300, 0xc109a0, 0xc420744340)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

The code in `context.go`
```
430 >---if err, ok := data.(error); ok {
431 >--->---if format == "" {
432 >--->--->---rw.Header().Set(runtime.HeaderContentType, runtime.JSONMime)
433 >--->---}
434 >--->---if route == nil || route.Operation == nil {
435 >--->--->---c.api.ServeErrorFor("")(rw, r, err)
436 >--->--->---return
437 >--->---}

438 >--->---c.api.ServeErrorFor(route.Operation.ID)(rw, r, err)

439 >--->---return
440 >---}
```

... which kinda leaves me at a dead-end.

**Comment by casualjim** [comment]
Is it the same spec from your previous issues?
Can you share the request you make that triggers this?

**Comment by SandyWalsh** [comment]
Slightly different https://gist.github.com/SandyWalsh/5987303142bea7bf5d41c07476dccf76

```
curl -i     -H "Accept: application/json"     -X POST     -d '{"id": "123e4567-e89b-12d3-a456-426655440000", "renditions": [], "bbox": {}, "coordinate_system": "coordinates", "first_acquired": "2006-01-02 15:04:05", "last_acquired": "2006-01-02 15:04:05", "product_type": "basemap", "name":"My mosaic"}'      http://127.0.0.1:8000/v1/mosaic/experimental/mosaics
```

I was hesitant to post the whole thing since it doesn't help me learn the flow of data through the system (give a man a fish, etc). Was really looking for tips that you use for debugging these sorts of problems. 

But I do appreciate you looking into it.

**Comment by SandyWalsh** [comment]
The error from `ServeErrorFor` seems to be 

```
validation failure list:
unsupported media type "application/x-www-form-urlencoded", only [application/json] are allowed
```

**Comment by casualjim** [comment]
ah you have to add a Content-Type header to your request.
This is a bug because it should return a 4xx status code

**Comment by SandyWalsh** [comment]
Thanks ... was very close to that myself (almost caught a fish ;)

**Comment by SandyWalsh** [comment]
It would be nice to get some debug level logging around that `ServeErrorFor()` line. For example, now I'm getting 

`parsing body body from "" failed, because json: cannot unmarshal object into Go value of type string`

when I issue
```
curl -i     -H "Accept: application/json" -H "Content-type: application/json"     -X POST     -d '{"id": "123e4567-e89b-12d3-a456-426655440000", "renditions": [], "bbox": {}, "coordinate_system": "coordinates", "first_acquired": "2006-01-02T15:04:05Z", "last_acquired": "2006-01-02T15:04:05Z", "product_type": "basemap", "name":"My mosaic"}'      http://127.0.0.1:8000/v1/mosaic/experimental/mosaics
```

... and it's tricky to determine what the offending field is.

**Comment by SandyWalsh** [comment]
Found it: `"bbox": ""` ... not `"bbox": {}` ... trial and error

**Comment by fredbi** [comment]
Stumbled today on that very old one...
Out of curiosity, I wanted to figure it out by myself.

Given the spec provided in the above gist, 
- omitting the `Content-Type application/json` header results in a 415 error, as expected
- the offending property type (`"bbox": {}`) is properly detected by the validator, returns a "400 bad request"
- the validation error message is explicit about what is wrong with that message
- providing the correct header and the correct input passes validation (reaches the "not implemented" handler)
- no panic occurred even with wrong input or headers

Although we sure could improve the server handler by providing more debugging instrumentation,
I think this may be closed now.
